// Mock data for development - replace with real API calls once database is set up

export const mockProjects = [
  {
    id: "1",
    github_owner: "paritytech",
    github_repo_name: "polkadot-sdk",
    github_repo_url: "https://github.com/paritytech/polkadot-sdk",
    description:
      "The Parity Polkadot Blockchain SDK - the core framework for building parachains and custom blockchains",
    website_url: "https://polkadot.network",
    logo_url: "/polkadot-logo.png",
    is_active: true,
    maintainer_user_id: "user1",
    created_at: "2024-01-15T10:00:00Z",
    profiles: {
      display_name: "Parity Technologies",
      avatar_url: "/parity-avatar.jpg",
    },
    tasks: [
      { id: "1", status: "open", reward_amount_dot: "50" },
      { id: "2", status: "open", reward_amount_dot: "75" },
      { id: "3", status: "in_progress", reward_amount_dot: "100" },
    ],
  },
  {
    id: "2",
    github_owner: "moonbeam-foundation",
    github_repo_name: "moonbeam",
    github_repo_url: "https://github.com/moonbeam-foundation/moonbeam",
    description: "An Ethereum-compatible smart contract parachain on Polkadot",
    website_url: "https://moonbeam.network",
    logo_url: "/moonbeam-logo.jpg",
    is_active: true,
    maintainer_user_id: "user2",
    created_at: "2024-01-20T10:00:00Z",
    profiles: {
      display_name: "Moonbeam Foundation",
      avatar_url: "/moonbeam-avatar.jpg",
    },
    tasks: [
      { id: "4", status: "open", reward_amount_dot: "30" },
      { id: "5", status: "open", reward_amount_dot: "45" },
    ],
  },
  {
    id: "3",
    github_owner: "AcalaNetwork",
    github_repo_name: "Acala",
    github_repo_url: "https://github.com/AcalaNetwork/Acala",
    description: "Acala - cross-chain DeFi hub and stablecoin platform powering the aUSD economy",
    website_url: "https://acala.network",
    logo_url: "/acala-logo.jpg",
    is_active: true,
    maintainer_user_id: "user3",
    created_at: "2024-02-01T10:00:00Z",
    profiles: {
      display_name: "Acala Network",
      avatar_url: "/acala-avatar.jpg",
    },
    tasks: [
      { id: "6", status: "open", reward_amount_dot: "60" },
      { id: "7", status: "open", reward_amount_dot: "40" },
      { id: "8", status: "open", reward_amount_dot: "80" },
    ],
  },
  {
    id: "4",
    github_owner: "subsquid",
    github_repo_name: "squid-sdk",
    github_repo_url: "https://github.com/subsquid/squid-sdk",
    description: "SDK for building custom data pipelines and APIs for Substrate chains",
    website_url: "https://subsquid.io",
    logo_url: "/subsquid-logo.jpg",
    is_active: true,
    maintainer_user_id: "user4",
    created_at: "2024-02-10T10:00:00Z",
    profiles: {
      display_name: "Subsquid",
      avatar_url: "/subsquid-avatar.jpg",
    },
    tasks: [{ id: "9", status: "open", reward_amount_dot: "25" }],
  },
  {
    id: "5",
    github_owner: "zeitgeistpm",
    github_repo_name: "zeitgeist",
    github_repo_url: "https://github.com/zeitgeistpm/zeitgeist",
    description: "Zeitgeist - decentralized prediction markets protocol built on Polkadot",
    website_url: "https://zeitgeist.pm",
    logo_url: "/zeitgeist-logo.jpg",
    is_active: true,
    maintainer_user_id: "user5",
    created_at: "2024-02-15T10:00:00Z",
    profiles: {
      display_name: "Zeitgeist PM",
      avatar_url: "/zeitgeist-avatar.jpg",
    },
    tasks: [
      { id: "10", status: "open", reward_amount_dot: "35" },
      { id: "11", status: "open", reward_amount_dot: "55" },
    ],
  },
  {
    id: "6",
    github_owner: "mock-user-1",
    github_repo_name: "polkadot-sdk",
    github_repo_url: "https://github.com/paritytech/polkadot-sdk",
    description: "The Parity Polkadot Blockchain SDK",
    is_active: true,
    maintainer_user_id: "mock-user-1",
    created_at: "2024-01-15T10:00:00Z",
    tasks: [
      { id: "1", status: "open", reward_amount_dot: "50" },
      { id: "2", status: "open", reward_amount_dot: "75" },
      { id: "3", status: "in_progress", reward_amount_dot: "100" },
    ],
  },
]

export const mockTasks = [
  {
    id: "1",
    project_id: "1",
    title: "Implement XCM v4 message format support",
    description:
      "Add support for the new XCM v4 message format in the runtime. This includes updating the message parser, adding new instruction types, and ensuring backward compatibility with v3.",
    github_issue_number: 1234,
    github_issue_url: "https://github.com/paritytech/polkadot-sdk/issues/1234",
    reward_amount_dot: "50",
    status: "open",
    difficulty: "intermediate",
    tags: ["rust", "xcm", "runtime"],
    created_at: "2024-03-01T10:00:00Z",
    projects: {
      github_repo_name: "polkadot-sdk",
      github_owner: "paritytech",
      logo_url: "/polkadot-logo.png",
    },
  },
  {
    id: "2",
    project_id: "1",
    title: "Add benchmarking tests for new pallet",
    description:
      "Create comprehensive benchmarking tests for the newly added governance pallet to ensure optimal performance.",
    github_issue_number: 1235,
    github_issue_url: "https://github.com/paritytech/polkadot-sdk/issues/1235",
    reward_amount_dot: "75",
    status: "open",
    difficulty: "advanced",
    tags: ["rust", "benchmarking", "testing"],
    created_at: "2024-03-02T10:00:00Z",
    projects: {
      github_repo_name: "polkadot-sdk",
      github_owner: "paritytech",
      logo_url: "/polkadot-logo.png",
    },
  },
  {
    id: "4",
    project_id: "2",
    title: "Fix EVM precompile gas calculation",
    description:
      "There's a bug in the gas calculation for certain EVM precompiles that causes transactions to fail. Need to identify and fix the issue.",
    github_issue_number: 567,
    github_issue_url: "https://github.com/moonbeam-foundation/moonbeam/issues/567",
    reward_amount_dot: "30",
    status: "open",
    difficulty: "intermediate",
    tags: ["rust", "evm", "bug-fix"],
    created_at: "2024-03-03T10:00:00Z",
    projects: {
      github_repo_name: "moonbeam",
      github_owner: "moonbeam-foundation",
      logo_url: "/moonbeam-logo.jpg",
    },
  },
  {
    id: "5",
    project_id: "2",
    title: "Update Ethereum compatibility documentation",
    description:
      "Update the documentation to reflect the latest Ethereum compatibility features and any breaking changes.",
    github_issue_number: 568,
    github_issue_url: "https://github.com/moonbeam-foundation/moonbeam/issues/568",
    reward_amount_dot: "45",
    status: "open",
    difficulty: "beginner",
    tags: ["documentation", "ethereum"],
    created_at: "2024-03-04T10:00:00Z",
    projects: {
      github_repo_name: "moonbeam",
      github_owner: "moonbeam-foundation",
      logo_url: "/moonbeam-logo.jpg",
    },
  },
  {
    id: "6",
    project_id: "3",
    title: "Implement new DeFi primitive for liquid staking",
    description:
      "Design and implement a new DeFi primitive that enables liquid staking with improved capital efficiency.",
    github_issue_number: 890,
    github_issue_url: "https://github.com/AcalaNetwork/Acala/issues/890",
    reward_amount_dot: "60",
    status: "open",
    difficulty: "advanced",
    tags: ["rust", "defi", "staking"],
    created_at: "2024-03-05T10:00:00Z",
    projects: {
      github_repo_name: "Acala",
      github_owner: "AcalaNetwork",
      logo_url: "/acala-logo.jpg",
    },
  },
  {
    id: "7",
    project_id: "3",
    title: "Add unit tests for oracle pallet",
    description: "Increase test coverage for the oracle pallet by adding comprehensive unit tests for all edge cases.",
    github_issue_number: 891,
    github_issue_url: "https://github.com/AcalaNetwork/Acala/issues/891",
    reward_amount_dot: "40",
    status: "open",
    difficulty: "intermediate",
    tags: ["rust", "testing", "oracle"],
    created_at: "2024-03-06T10:00:00Z",
    projects: {
      github_repo_name: "Acala",
      github_owner: "AcalaNetwork",
      logo_url: "/acala-logo.jpg",
    },
  },
  {
    id: "8",
    project_id: "3",
    title: "Optimize transaction batching logic",
    description: "Improve the performance of transaction batching to reduce gas costs and increase throughput.",
    github_issue_number: 892,
    github_issue_url: "https://github.com/AcalaNetwork/Acala/issues/892",
    reward_amount_dot: "80",
    status: "open",
    difficulty: "advanced",
    tags: ["rust", "optimization", "performance"],
    created_at: "2024-03-07T10:00:00Z",
    projects: {
      github_repo_name: "Acala",
      github_owner: "AcalaNetwork",
      logo_url: "/acala-logo.jpg",
    },
  },
  {
    id: "9",
    project_id: "4",
    title: "Add support for new Substrate storage format",
    description:
      "Update the indexer to support the new Substrate storage format introduced in the latest runtime upgrade.",
    github_issue_number: 345,
    github_issue_url: "https://github.com/subsquid/squid-sdk/issues/345",
    reward_amount_dot: "25",
    status: "open",
    difficulty: "intermediate",
    tags: ["typescript", "indexer", "substrate"],
    created_at: "2024-03-08T10:00:00Z",
    projects: {
      github_repo_name: "squid-sdk",
      github_owner: "subsquid",
      logo_url: "/subsquid-logo.jpg",
    },
  },
  {
    id: "10",
    project_id: "5",
    title: "Implement market resolution dispute mechanism",
    description:
      "Add a dispute resolution mechanism for prediction markets that allows users to challenge incorrect market resolutions.",
    github_issue_number: 678,
    github_issue_url: "https://github.com/zeitgeistpm/zeitgeist/issues/678",
    reward_amount_dot: "35",
    status: "open",
    difficulty: "advanced",
    tags: ["rust", "governance", "markets"],
    created_at: "2024-03-09T10:00:00Z",
    projects: {
      github_repo_name: "zeitgeist",
      github_owner: "zeitgeistpm",
      logo_url: "/zeitgeist-logo.jpg",
    },
  },
  {
    id: "11",
    project_id: "5",
    title: "Create tutorial for market creation",
    description:
      "Write a comprehensive tutorial that guides users through the process of creating and managing prediction markets.",
    github_issue_number: 679,
    github_issue_url: "https://github.com/zeitgeistpm/zeitgeist/issues/679",
    reward_amount_dot: "55",
    status: "open",
    difficulty: "beginner",
    tags: ["documentation", "tutorial"],
    created_at: "2024-03-10T10:00:00Z",
    projects: {
      github_repo_name: "zeitgeist",
      github_owner: "zeitgeistpm",
      logo_url: "/zeitgeist-logo.jpg",
    },
  },
]

export const mockUserProfile = {
  id: "mock-user-1",
  email: "developer@example.com",
  display_name: "Alex Developer",
  avatar_url: "/default-avatar.jpg",
  github_username: "alexdev",
  wallet_address: "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
  role: "developer",
  created_at: "2024-01-01T10:00:00Z",
}

export const mockContributions = [
  {
    id: "contrib-1",
    task_id: "1",
    contributor_user_id: "mock-user-1",
    github_pr_url: "https://github.com/paritytech/polkadot-sdk/pull/5678",
    github_pr_number: 5678,
    status: "approved",
    submitted_at: "2024-03-15T10:00:00Z",
    reviewed_at: "2024-03-16T10:00:00Z",
    tasks: {
      id: "1",
      title: "Implement XCM v4 message format support",
      reward_amount_dot: "50",
      projects: {
        github_repo_name: "polkadot-sdk",
      },
    },
  },
  {
    id: "contrib-2",
    task_id: "4",
    contributor_user_id: "mock-user-1",
    github_pr_url: "https://github.com/moonbeam-foundation/moonbeam/pull/1234",
    github_pr_number: 1234,
    status: "pending",
    submitted_at: "2024-03-18T10:00:00Z",
    reviewed_at: null,
    tasks: {
      id: "4",
      title: "Fix EVM precompile gas calculation",
      reward_amount_dot: "30",
      projects: {
        github_repo_name: "moonbeam",
      },
    },
  },
  {
    id: "contrib-3",
    task_id: "7",
    contributor_user_id: "mock-user-1",
    github_pr_url: "https://github.com/AcalaNetwork/Acala/pull/2345",
    github_pr_number: 2345,
    status: "approved",
    submitted_at: "2024-03-12T10:00:00Z",
    reviewed_at: "2024-03-14T10:00:00Z",
    tasks: {
      id: "7",
      title: "Add unit tests for oracle pallet",
      reward_amount_dot: "40",
      projects: {
        github_repo_name: "Acala",
      },
    },
  },
]

export const mockUserProjects = [
  {
    id: "1",
    github_owner: "paritytech",
    github_repo_name: "polkadot-sdk",
    github_repo_url: "https://github.com/paritytech/polkadot-sdk",
    description: "The Parity Polkadot Blockchain SDK",
    is_active: true,
    maintainer_user_id: "mock-user-1",
    created_at: "2024-01-15T10:00:00Z",
    tasks: [
      { id: "1", status: "open", reward_amount_dot: "50" },
      { id: "2", status: "open", reward_amount_dot: "75" },
      { id: "3", status: "in_progress", reward_amount_dot: "100" },
    ],
  },
]
